version: '3'

services:

  medcool-nodejs:
    container_name: nodejs-medcool
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres:
    container_name: postgres-medcool
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    ports:
      - '5432:5432'
    networks:
      - app-connect

volumes:
  postgres-data:

    null
networks:
  app-connect:
    driver: bridge
