version: '3'

services:
  nodejs:
    build: .
    container_name: backend
    restart: always
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=postgresdb
      - DB_NAME=$DB_NAME
    ports:
      - '3333:3333'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/app
    networks:
      - postgres-network
    command: npm run dev

  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dbdata:/data/db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  dbdata:
